#!env python



try:
    import readline
    readline.parse_and_bind('tab:complete')
except Exception as e:
    print(e)

try:
    import sh
except Exception as e:
    print(e)


try:
    from xilio import *
except Exception as e:
    print(e)
